[package]
authors = ["i5hi, mocodesmo"]
description = "Rust-C FFI exposing composite functionality to build bitcoin descriptor wallets."
edition = "2018"
keywords = ["bitcoin", "rust-c-ffi"]
license = "MIT"
name = "stackmate"
version = "0.7.15"

[dependencies]
bip39 = "1.0.1"
hex = "0.4.3"
openssl = {version = "*", features = ["vendored"]}
openssl-sys = {version = "*", features = ["vendored"]}
libtor = "46.6.1+0.4.6.6"
serde = "1.0.126"
serde_derive = "1.0.0"
serde_json = "1.0.64"
sha-1 = "0.9.8"
secp256k1 = {version = "0.21.3", features = ["rand","bitcoin_hashes", "global-context", "rand-std"]}

[dependencies.bdk]
features = ["compiler", "rpc", "electrum"]
version = "0.16.1"

[dependencies.bitcoin]
features = ["rand", "base64"]
version = "0.27.1"

[lib]
crate-type = ["staticlib", "cdylib"]
name = "stackmate"

# [profile]
# [profile.release]
# codegen-units = 1
# lto = true
# opt-level = "z"
# panic = "abort"

# [target.aarch64-linux-android.dependencies.openssl]
# features = ["vendored"]
# version = "*"

# [target.i686-linux-android.dependencies.openssl]
# features = ["vendored"]
# version = "*"

# [target.x84_64-linux-android.dependencies.openssl]
# features = ["vendored"]
# version = "*"

# [target.x86_64-apple-ios.dependencies.openssl]
# features = ["vendored"]
# version = "*"

# [target.aarch64-apple-ios.dependencies.openssl]
# features = ["vendored"]
# version = "*"

# [target.armv7-apple-ios.dependencies.openssl]
# features = ["vendored"]
# version = "*"

# [target.armv7s-apple-ios.dependencies.openssl]
# features = ["vendored"]
# version = "*"

# [target.i386-apple-ios.dependencies.openssl]
# features = ["vendored"]
# version = "*"
