[package]
authors = ["i5hi, mocodesmo"]
description = "Rust-C FFI exposing composite functionality to build bitcoin descriptor wallets."
edition = "2018"
keywords = ["bitcoin", "rust-c-ffi"]
license = "MIT"
name = "stackmate"
version = "0.8.2"

[dependencies]
base32 = "0.4.0"
base64 = "0.13.0"
bip39 = "1.0.1"
hex = "0.4.3"
serde = "1.0.126"
serde_derive = "1.0.0"
serde_json = "1.0.64"
sha-1 = "0.10.0"
chacha20poly1305 = { version = "0.9.0", features = ["stream"] }

[dependencies.secp256k1]
features = ["rand", "bitcoin_hashes", "global-context", "rand-std"]
version = "0.22.0"

[dependencies.bitcoin]
features = ["rand", "base64"]
version = "0.27.1"

[dependencies.bdk]
features = ["compiler", "rpc", "electrum"]
version = "0.16.1"


[lib]
crate-type = ["staticlib", "cdylib"]
name = "stackmate"

[release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"

[target]
[target.aarch64-apple-ios]
[target.aarch64-apple-ios.dependencies]
[target.aarch64-apple-ios.dependencies.openssl]
features = ["vendored"]
version = "*"

[target.aarch64-linux-android]
[target.aarch64-linux-android.dependencies]
[target.aarch64-linux-android.dependencies.openssl]
features = ["vendored"]
version = "*"

[target.i686-linux-android]
[target.i686-linux-android.dependencies]
[target.i686-linux-android.dependencies.openssl]
features = ["vendored"]
version = "*"

[target.x84_64-linux-android]
[target.x84_64-linux-android.dependencies]
[target.x84_64-linux-android.dependencies.openssl]
features = ["vendored"]
version = "*"

[target.x86_64-apple-ios]
[target.x86_64-apple-ios.dependencies]
[target.x86_64-apple-ios.dependencies.openssl]
features = ["vendored"]
version = "*"
